---
title: "grene-net flowering data"
output: html_document
author: Moi
date: May 16 2020
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/safedata/ath_evo/grenephase1/")

knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpmisc)
library(cowplot)
theme_set(theme_cowplot())
library(RColorBrewer)
library(tidyverse)
# devtools::install("~/safedata/genemaps/")
library(genemaps)

# Grene net
devtools::load_all(".")

```

```{r}
data("recordssorted")

# Get the year from date
df <- recordssorted %>%
        mutate(year= year(D))  

# Transform the records to weight more those samples that had more flowers
df<- df %>%
  # group by site and year
  dplyr::group_by(SITE,year) %>%
  # make flowers numeric and filter those that have more than 1
  mutate(NUMBER_FLOWERS_COLLECTED = as.numeric(NUMBER_FLOWERS_COLLECTED)) %>%
  dplyr::filter(NUMBER_FLOWERS_COLLECTED>=1) %>%
  # Get the date to day within year
  mutate(startyear=as.Date(paste0(year,"0101"),format="%Y%m%d")) %>%
  mutate(dayofyear=D-startyear) %>%
  # get the fraction of flowers collected
  mutate(fracflowers=NUMBER_FLOWERS_COLLECTED/sum(NUMBER_FLOWERS_COLLECTED))

# Summarize per site and year, and season
dfmean<- df %>%
    dplyr::mutate(season=ifelse(dayofyear>230 | dayofyear<20, "fall","spring")) %>% # These are the typical fall ranges
    dplyr::group_by(SITE,year,season) %>%
    summarize(wmean=as.numeric(sum(dayofyear*fracflowers,na.rm = T)),
              wvar=sum(as.numeric((dayofyear - sum(dayofyear*fracflowers,na.rm = T)))^2 * fracflowers)
              )
    
plot(dfmean$wvar,dfmean$wmean)
hist(dfmean$wmean)


data("sitesinfo")
toplot<-merge(dfmean,sitesinfo,by.x='SITE', by.y="SITE_CODE") %>%
          dplyr::mutate(LATITUDE=fn(LATITUDE),
                        wmean=fn(wmean)) %>% 
          dplyr::select(LATITUDE,wmean, wvar, year) %>%
          na.omit
head(toplot)

ggplot(toplot) +
  geom_point(aes(x=wmean,y=LATITUDE)) +
  stat_smooth(aes(x=wmean,y=LATITUDE),method='glm',se=F,color='grey') +
  facet_wrap(~year)+
  labs(y='Latitude (deg N)', x='weigted mean flowering (day of year)')


#### change from one year to next
dfmean %>%
  dplyr::select(-wvar) %>%
  spread(key="year",value="wmean") ->
  ftcompare
ftcompare
  
wmean %>%
  dplyr::select(-wmean) %>%
  spread(key="year",value="varflo") ->
  ftcompare2

```

Write out table
```{r}

write.csv(file = 'tables/preliminary_flowering_peaks_GrENE-net.csv',towrite)

```


# Maxent realized niche
use the 2029 locations with arabidopsis accessions or GBIF
```{r}
library(dismo)
library(raster)
library(randomForest)
# global arabidopsis locations
load("~/safedata/ath_1001G_field/field/data/gbif.rda")
head(gbif)
gbif <- gbif  %>% 
  dplyr::filter(lat >euroextents()$ylim[1],
                lat <euroextents()$ylim[2],
                lon >euroextents()$xlim[1],
                lon <euroextents()$xlim[2],
                )%>%
  dplyr::sample_n(5000)
head(gbif)
train<-gbif %>% rename(x=lon,y=lat)
train$pa<-1

# get the predictors
predictors<-getData('worldclim', var='bio', res=2.5,path='~/natvar')
predictors<-cropenvironment(predictors)

# sample background points
bg <- randomPoints(predictors, 10000) %>% 
  data.frame
bg$pa<-0
head(bg)

# extract environment
tofit<-rbind(train,bg)
myenv <- data.frame(raster::extract(predictors, tofit[,c("x","y")]))
head(myenv)

tofit<-data.frame(pa=tofit$pa,myenv)
head(tofit)
tofit<-na.roughfix(tofit)

# fit model
maxmod<-randomForest(formula=pa~.,data=tofit)
maxmod

# extrapolate to map
rall <- raster::predict(object = getData('worldclim', var='bio', res=2.5,path='~/natvar'), maxmod)
r <- raster::predict(object = predictors, maxmod)
raster::plot(r)

pdf("figs/rfmaxent_5k_5k.pdf",width = 5,height = 5)
envirplot(r, vecol = brewer.pal(9,"Greens")[-1],numbreak = 3,dimcol = 10,contrast = F)
dev.off()


# a bit nicer plot
projectionCRS <- CRS("+proj=laea +lon_0=0.001 +lat_0=89.999 +ellps=sphere")
rallnorthern <- projectRaster(rall, crs=projectionCRS)
# raster::plot(rallnorthern)
pdf("figs/rfmaxent_5k_5k_northprojection.pdf",width = 5,height = 5)
envirplot(rallnorthern, vecol = brewer.pal(9,"Greens")[-1],numbreak = 3,dimcol = 10,contrast = F)
dev.off()

```


Is the MaxEnt model good at predicting habitat suitability?
```{r}
successsummary<-read.table("tables/success_summary.tsv",header = T)
head(successsummary)

predsuccess <- data.frame(raster::extract(r, successsummary[,c("LONGITUDE","LATITUDE")]))

successsummary$suitability <- fn(predsuccess)
head(successsummary)


qplot(successsummary$colorscale ~ successsummary$suitability)
ggplot(successsummary) +
  stat_summary(aes(y=suitability, x=colorscale,group=colorscale), color=transparent("grey"))+
  geom_jitter(aes(y=suitability, x=colorscale,group=colorscale, color=factor(colorscale) ),width = 0.1, size=3.5) +
  scale_color_manual(values=successcolor)+
  labs(y="Habitat suitability", x="Experiment success")


```

```{r}
successsummary<-read.table("tables/success_summary.tsv",header = T)
successclimate <- data.frame(raster::extract(predictors, successsummary[,c("LONGITUDE","LATITUDE")]))
successclimate <- cbind(successsummary, successclimate)
head(successclimate)

lm(colorscale ~ bio1+bio12 , data=successclimate) %>% 
  summary

successclimate<-na.roughfix(successclimate)
randomForest(colorscale ~ ., data=successclimate[,-1]) 

```


How much variance can climate variables explain?
```{r}
library(randomForest)
as.matrix(colnames(m))
climvars<-c(paste0("bio",1:19),paste0("prec",1:12),paste0("tmin",1:12),paste0("tmax",1:12))
climvars<-c(paste0("bio",1:19))

tomodel<- m[,colnames(m) %in% c("NUMBER_FLOWERS_COLLECTED",climvars)] 
tomodel<- m[,colnames(m) %in% c("NUMBER_FLOWERS_COLLECTED",climvars,"doy")] 
tomodel<-na.roughfix(tomodel)
rm<-randomForest(NUMBER_FLOWERS_COLLECTED ~ ., data = tomodel)
rm

predict(data.frame())
flower_n_dayofyear

ggplot(m) +
  
```



# Fit number of plants by climate!
```{r}
library(raster)

myproj<-
sapply(seq(30,120, by=10), function(i){
  doy<-eupred[[1]]
  names(doy)<-"doy"
  values(doy)[!is.na(values(doy))] <-i
  
  newpred<-stack(eupred,doy)
  names(newpred)
  
  predpop<-raster::predict(object=newpred,rm)
})
myproj2<-stack(myproj)

raster::plot(myproj2[[5]])

for(i  in 1:length(names(myproj2))){
  png()
}

doy<-eupred[[1]]
names(doy)<-"doy"
values(doy)[!is.na(values(doy))] <-90

newpred<-stack(eupred,doy)
names(newpred)

predpop<-raster::predict(object=newpred,rm)
raster::plot(predpop)


```
