# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title
#'
#' @param x
#' @param n
#' @param p
#'
#' @return
#' @export
#'
#' @examples
freqtest <- function(x, n, p) {
    .Call('_grene_freqtest', PACKAGE = 'grene', x, n, p)
}

